build:
  version: "2.0"

cards:
  message: "Welcome to SamBank cards related QA APIs "
  contactDetails:
    name: "Samridhi Parihar - QA Lead"
    email: "samridhiparihar@sambank.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267